[package]
name = "sabiniwm"
description = "A tiling Wayland compositor, influenced xmonad"
documentation = "https://docs.rs/sabiniwm"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

[dependencies]
backtrace = { workspace = true }
big_s = { workspace = true }
bitflags = { workspace = true }
derive_more = { workspace = true }
downcast = { workspace = true }
dyn-clone = { workspace = true }
envy = { workspace = true }
eyre = { workspace = true }
itertools = { workspace = true }
maplit = { workspace = true }
procfs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smithay = { workspace = true }
smithay-drm-extras = { workspace = true, optional = true }
thin_delegate = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
x11rb = { workspace = true, optional = true }
xcursor = { workspace = true, optional = true }
xkbcommon = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[features]
default = ["egl", "udev_deps", "winit", "xwayland"]
debug_session_lock_client_dead = []
egl = ["smithay/use_system_lib", "smithay/backend_egl"]
# Only enables additional feature flags and doesn't affect to code.
udev_deps = [
  "smithay-drm-extras",
  "smithay/backend_libinput",
  "smithay/backend_udev",
  "smithay/backend_drm",
  "smithay/backend_gbm",
  "smithay/backend_vulkan",
  "smithay/backend_egl",
  "smithay/backend_session_libseat",
  "smithay/renderer_gl",
  "smithay/renderer_pixman",
  "smithay/renderer_multi",
  "xcursor",
]
winit = ["smithay/backend_winit", "smithay/backend_drm"]
xwayland = ["smithay/xwayland", "x11rb", "smithay/x11rb_event_source", "xcursor"]
